config/routes.rb
Rails.application.routes.draw do
    
    devise_for :user
    root 'freelancers#index'

    #메인페이지
    get 'index' => 'freelancers#index'
    get 'new' => 'freelancers#new'
    post 'category' => 'freelancers#category'
    get 'ready' => 'freelancers#ready'
    get 'about' => 'freelancers#about'
    
    #영상관련
    get 'video' => 'freelancers#video'
    get 'video/show/:id' => 'freelancers#video_show'
    get 'video/new' => 'freelancers#video_new'
    post 'video/create' => 'freelancers#video_create'
    get 'video/:id/edit' => 'freelancers#video_edit'
    patch 'video/show/:id/update' => 'freelancers#video_update'
    get 'video/show/:id/delete' => 'freelancers#video_destroy'
    
    #디자인관련
    get 'design' => 'freelancers#design'
    get 'design/show/:id' => 'freelancers#design_show'
    get 'design/new' => 'freelancers#design_new'
    post 'design/create' => 'freelancers#design_create'
    get 'design/:id/edit' => 'freelancers#design_edit'
    patch 'design/show/:id/update' => 'freelancers#design_update'
    get 'design/show/:id/delete' => 'freelancers#design_destroy'
    
    #홍보관련
    get 'promotion' => 'freelancers#promotion'
    post 'promotion/create' => 'freelancers#promotion_create'
    get 'promotion/:id/delete' => 'freelancers#promotion_delete'
    
    #로그인관련
    get 'login', to: redirect('/auth/google_oauth2'), as: 'login'
    get 'logout', to: 'sessions#destroy', as: 'logout'
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'me', to: 'me#show', as: 'me'
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController
  
  def index
  end
  
  def new
    if !user_signed_in?
      flash[:alert] = "로그인이 필요합니다!"
      redirect_to new_user_session_path
    elsif !current_user.has_role? :admin
      flash[:alert] = "작성권한이 없습니다"
      redirect_to root_path
    end
  end
  
  def category
    @category = Category.new(category_new)
  
    if (@category.category == "영상")
      redirect_to video_new_path
    elsif (@category.category == "디자인")
      redirect_to design_new_path
    end
  end
  
  def ready
  end
  
  def about
  end
  
  def video
    @videos = Video.all
    # <%= p.portfolio_url.split('.')[-1] %>
  end
  
  def video_new
    @video = Video.new
    @video_attachment = @video.video_attachments.build
  end
  
  def video_edit
    if !user_signed_in?
      flash[:alert] = "로그인이 필요합니다!"
      redirect_to new_user_session_path
    elsif !current_user.has_role? :admin
      flash[:alert] = "권한이 없습니다"
      redirect_to :back
    else
      @video = Video.find(params[:id])
    end
  end
  
  def video_create
    @video = Video.new(video_params)
    
    respond_to do |format|
      if @video.save
        params[:video_attachments]['portfolio'].each do |a|
          @video_attachment = @video.video_attachments.create!(:portfolio => a, :video_id => @video.id)
        end
        format.html { redirect_to action: "video_show", id: @video.id, notice: 'Video was successfully created.' }
      end
    end
  end
  
  def video_show
    @video = Video.find(params[:id])
    @video_attachments = @video.video_attachments.all
  end
  
  def video_update
    @video = Video.find(params[:id])
        
    respond_to do |format|
      if @video.update(video_update_params)
        @video.video_attachments.all.each do |attachment|
          attachment.remove_portfolio!
          attachment.destroy
        end
  
        params[:video_attachments]['portfolio'].each do |a|
          @video_attachment = @video.video_attachments.create!(:portfolio => a, :video_id => @video.id)
        end
        format.html { redirect_to action: "video_show", id: @video.id, notice: 'Video was successfully updated.' }
      end
    end
  end
  
  def video_destroy
    if !user_signed_in?
      flash[:alert] = "로그인이 필요합니다!"
      redirect_to new_user_session_path
    elsif !current_user.has_role? :admin
      flash[:alert] = "권한이 없습니다"
      redirect_to :back
    else
      @video = Video.find(params[:id])
      
      @video.remove_locallage!
     
      @video.video_attachments.each do |attachment|
        attachment.remove_portfolio!
      end
      
      @video.destroy
      
      respond_to do |format|
        format.html { redirect_to action: "video", notice: 'Video was successfully destroyed.' }
      end
    end
  end
  
  def design
    @designs = Design.all
  end
  
  def design_new
    @design = Design.new
    @design_attachment = @design.design_attachments.build
  end
  
  def design_edit
    if !user_signed_in?
      flash[:alert] = "로그인이 필요합니다!"
      redirect_to new_user_session_path
    elsif !current_user.has_role? :admin
      flash[:alert] = "권한이 없습니다"
      redirect_to :back
    else
      @design = Design.find(params[:id])
    end
  end
  
  def design_create
    @design = Design.new(design_params)
    
    respond_to do |format|
      if @design.save
        params[:design_attachments]['portfolio'].each do |a|
          @design_attachment = @design.design_attachments.create!(:portfolio => a, :design_id => @design.id)
        end
        format.html { redirect_to action: "design_show", id: @design.id, notice: 'Design was successfully created.' }
      end
    end
  end
  
  def design_show
    @design = Design.find(params[:id])
    
    @design_attachments = @design.design_attachments.all
  end
  
  def design_update
    @design = Design.find(params[:id])
    
    respond_to do |format|
      if @design.update(design_update_params)
        @design.design_attachments.all.each do |attachment|
          attachment.remove_portfolio!
          attachment.destroy
        end
  
        params[:design_attachments]['portfolio'].each do |a|
          @design_attachment = @design.design_attachments.create!(:portfolio => a, :design_id => @design.id)
        end
        format.html { redirect_to action: "design_show", id: @design.id, notice: 'Design was successfully updated.' }
      end
    end
  end
  
  def design_destroy
    if !user_signed_in?
      flash[:alert] = "로그인이 필요합니다!"
      redirect_to new_user_session_path
    elsif !current_user.has_role? :admin
      flash[:alert] = "권한이 없습니다"
      redirect_to :back
    else
      @design = Design.find(params[:id])
      
      @design.remove_locallage!
     
      @design.design_attachments.each do |attachment|
        attachment.remove_portfolio!
      end
      
      @design.destroy
      
      respond_to do |format|
        format.html { redirect_to action: "design", notice: 'Design was successfully destroyed.' }
      end
    end
  end
  
  
  def promotion
    @promotions = Promotion.all
    
    @promotion = Promotion.new
  end
  
  def promotion_create
    @promotion = Promotion.new(promotion_params)
    
    @promotion.save
    
    redirect_to promotion_path
  end
  
  def promotion_delete
    if !user_signed_in?
      flash[:alert] = "로그인이 필요합니다!"
      redirect_to new_user_session_path
    elsif !current_user.has_role? :admin
      flash[:alert] = "권한이 없습니다"
      redirect_to :back
    else
      promotion = Promotion.find (params[:id])
      promotion.destroy
      
      redirect_to :back
    end
  end
  
  private
    def category_new
      params.require(:category).permit(:category)
    end
    
    def video_params
      params.require(:video).permit(:title, :university, :grade, :name, :content, :video_url, :locallage, :user_id, video_attachments_attributes: [:id, :video_id, :portfolio])
    end
    
    def design_params
      params.require(:design).permit(:title, :university, :grade, :name, :content, :locallage, :user_id, design_attachments_attributes: [:id, :design_id, :portfolio])
    end
    
    def video_update_params
      params.require(:video).permit(:title, :university, :grade, :name, :content, :video_url, :locallage, video_attachments_attributes: [:id, :video_id, :portfolio])
    end
    
    def design_update_params
      params.require(:design).permit(:title, :university, :grade, :name, :content, :locallage, design_attachments_attributes: [:id, :design_id, :portfolio])
    end
    
    def promotion_params
      params.require(:promotion).permit(:title, :category, :blog)
    end
      
end

app/helpers/freelancers_helper.rb
module FreelancersHelper
end

app/views/freelancers/about.html.erb
<div class="container">
    <div class="about">
        <img src="<%= asset_path( 'about-page.png' ) %>" alt="logo" />
    </div>
</div>

app/views/freelancers/design.html.erb
<div class="index">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <div class="category">
                    <img src="<%= asset_path( 'design-index.png' ) %>" /><br>
                    <img src="<%= asset_path( 'login-bar1.png' ) %>" /><br>
                    <img src="<%= asset_path( 'category.png' ) %>" /><br>
                    <img src="<%= asset_path( 'login-bar3.png' ) %>" /><br>
                </div>
            </div>
            
            <div class="col-8">
                <div>
                    <img src="<%= asset_path( 'design-category.png' ) %>" />
                </div>
                <div>
                    <% @designs.each do |design| %>
                        <div class="product-list">
                            <a href="design/show/<%= design.id %>">
                                <div class="row">
                                    <div class="col-4">
                                        <div class="index-image">
                                            <img src="<%= design.locallage.medium.url %>" />
                                        </div>
                                    </div>
                                    <div class="col-8">
                                        <div class="product-content">
                                            <p class="index-title">
                                                <%= design.title %>
                                            </p>
                                            <hr>
                                            <p>
                                                <span class="index-university"><%= design.university %>대학교</span>
                                                <span class="index-grade"><%= design.grade %>학년</span>
                                                <span class="index-name"><%= design.name %></span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/freelancers/design_edit.html.erb
<%= form_for(@design, :html => { :multipart => true }, url: "/design/show/#{@design.id}/update", method: :patch ) do |f| %>

    <%= f.label :locallage %>
    <%= f.file_field :locallage %>
    
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :university %>
    <%= f.text_field :university %>
    
    <%= f.label :grade %>
    <%= f.text_field :grade %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
      
    <%= f.label :content %>
    <%= f.text_area :content %>
      

    <%= f.fields_for :design_attachments do |p| %>
      <div class="field">
        <%= p.label :portfolio %><br>
        <%= p.file_field :portfolio, :multiple => true, name: "design_attachments[portfolio][]" %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/freelancers/design_new.html.erb
<div class="new-content">
  <div class="container">
    <%= form_for(@design, :html => { :multipart => true }, url: design_create_path) do |f| %>
        
      <%= f.label :locallage %>
      <%= f.file_field :locallage %>
        
      <%= f.label :title %>
      <%= f.text_field :title %>
      
      <%= f.label :university %>
      <%= f.text_field :university %>
      
      <%= f.label :grade %>
      <%= f.text_field :grade %>
      
      <%= f.label :name %>
      <%= f.text_field :name %>
      
      <%= f.label :content %>
      <%= f.text_area :content %>
      
      <%= f.hidden_field :user_id, value: current_user.id %>
        
      <%= f.fields_for :design_attachments do |p| %>
      <div class="field">
        <%= p.label :portfolio %><br>
        <%= p.file_field :portfolio, :multiple => true, name: "design_attachments[portfolio][]" %>
      </div>
    <% end %>
    
    <div class="actions">
      <%= f.submit %>
    </div>
        <% end %>
   </div>
</div>

app/views/freelancers/design_show.html.erb
<div class="detail">
  <div class="container">
    
    <!-- 어드민 수정/삭제 기능 버튼 -->
    <% if !current_user.nil? %>
      <% if ((current_user.id == @design.user_id) || (current_user.has_role? :admin)) %>
        <a href="../<%= @design.id %>/edit">수정</a>
        <a href="../show/<%= @design.id %>/delete">삭제</a>
      <% end %>
    <% end %>
    
    <div class="row">
      
      <div class="col-7">
        
        <!-- 개인 페이지의 이미지 -->
        <div class="detail-image">
          <img src="<%= @design.locallage.personal.url %>">
        </div>
        
        <!-- 가격, 수정사항, 환불 규정-->
        <div class="detail-information">
          <div class="row">
            <div class="col detail-information1"><a onclick="mostrar(0);">가격정보</a></div>
            <div class="col detail-information2"><a onclick="mostrar(1);">수정사항</a></div>
            <div class="col detail-information3"><a onclick="mostrar(2);">취소 및 환불규정</a></div>
          </div>
        </div>
        
        <!-- 가격, 수정사항, 환불 규정 세부사항-->
        <div class="detail-information-content">
          <div class="detail-price">
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">디자인정보</th>
                  <th scope="col">디자인내역</th>
                  <th scope="col">가격</th>
                  <th scope="col">기간</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>로고디자인</td>
                  <td>텍스트형2종 + 심볼형1종</td>
                  <td>100,000원</td>
                  <td>2~3일</td>
                </tr>
                <tr>
                  <td>명함디자인</td>
                  <td>명함디자인 2종</td>
                  <td>40,000원</td>
                  <td>2~3일</td>
                </tr>
                <tr>
                  <td>PPT디자인</td>
                  <td>PPT디자인</td>
                  <td>장당 5,000원</td>
                  <td>2~3일</td>
                </tr>
                <tr>
                  <td>현수막디자인</td>
                  <td>현수막디자인</td>
                  <td>30,000원</td>
                  <td>2~3일</td>
                </tr>
                <tr>
                  <td>포스터디자인</td>
                  <td>포스터디자인(A2, A4)</td>
                  <td>80,000원</td>
                  <td>2~3일</td>
                </tr>
              </tbody>
            </table>
          </div>
          
          <div class="hide detail-fix">
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th scope="col">기본 수정 규정</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>무료 수정 기본 2회 진행</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>2차 시안 이후 수정은 색상 및 크기변경, 위치변경 등 간단한 수정만 가능</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>1차 시안 이후 환불 60%, 2차 시안 이후 환불 불가</td>
                </tr>
              </tbody>
            </table> 
          </div>
          
          <div class="hide detail-refund">
            <table class="table">
              <thead>
                <tr>
                  <th></th>
                  <th scope="col"> 취소 및 환불 규정</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1</td>
                  <td>전문가와 의뢰인 간의 상호 협의 후 청약철회가 가능</td>
                </tr>
                <tr>
                  <td>2</td>
                  <td>전문가의 귀책사유로 디자인 작업이 시작되지 않았거나 보편적 관점에서 심각하게 잘못 이행한 경우 결제 금액 전체 환불이 가능</td>
                </tr>
                <tr>
                  <td>3</td>
                  <td>전문가가 작업 기간 동안 지정된 서비스를 제공하지 못한 경우 지급받은 서비스 비용을 일할 계산하여 작업물 개수와 작업기간 일수만큼 공제하고 잔여 금액을 환불합니다</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
        
        <!-- 상세설명 -->
        <div class="detail-content">
          <hr>
          <%= h(@design.content).gsub(/\n/, '<br/>').html_safe %>
          <hr>
        </div>
        
        <!-- 포트폴리오 -->
        <div class="postfolio">
          <% @design_attachments.each do |p| %>
            <div class="portfolio-each">
                <img src="<%= p.portfolio_url %>" width=600 /><br>
            </div>
            <!--<?%= link_to "Edit Attachment", _path(p) %>-->
          <% end %>
        </div>
      </div>
      
      <div class="col-3">
        
        <!-- 개인페이지 상태바 -->
        
        <!-- 개인페이지 제목 -->
        <div class="detail-title">
          <b><%= @design.title %></b>
        </div>
        
        <!-- 개인페이지 상태바 세부 -->
        <div class="detail-status">
          <div class="status-1">
            DESIGN &emsp;&emsp;&emsp;&emsp;<i class="fas fa-angle-down"></i>
          </div>
          <div class="status-2">
            <div class="detail-university">
              <%= @design.university %>대학교
            </div>
            <div class="detail-grade">
              <%= @design.grade %>학년
            </div>
            <div class="detail-name">
              <%= @design.name %>
            </div>
            <hr class="divider">
            <div class="detail-fixcontent">
              <i class="fas fa-check" style="color:orange"></i> 원본 파일 제공 <i class="fas fa-check" style="color:orange"></i> 무료 수정 2회 제공<br>
              <i class="fas fa-check" style="color:orange"></i> 시안 개수 : 2개
            </div>
            <div class="detail-day">
              <i class="far fa-calendar-alt"></i> 작업일 : 2 ~ 3일
            </div>
            
            <div class="detail-buy">
              <a href="http://pf.kakao.com/_wEdxej/chat" target="_blank"><img src="<%= asset_path( 'matching.jpg' ) %>" /></a>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  /* 수정, 가격 및 환불 설명창 변경 스크립트*/
  function mostrar(order) {
    switch (order) {
        case 0:
            $(".hide").removeClass("show");
            $(".detail-price").addClass("show");
            break;
        case 1:
            $(".hide").removeClass("show");
            $(".detail-fix").addClass("show");
            $(".detail-price").addClass("hide");
            break;
        case 2:
            $(".hide").removeClass("show");
            $(".detail-refund").addClass("show");
            $(".detail-price").addClass("hide");
            break;
    }
  }
</script>

app/views/freelancers/index.html.erb
<div class='main'>
    <div class='container'>
        <div class='main-title'>
                <h1><b>로컬리지 <span class='main-title-focus'>소개</span></b></h1>
        </div>
        <div class='main-image'>
            <img src="<%= asset_path( 'mainpage.png' ) %>" />
            <div class='main-image-text'>
                <div class='row'>
                    <div class='col text1'>
                        스타트업
                    </div>
                    <div class='col text2'>
                        로컬리지
                    </div>
                    <div class='col text3'>
                        대학생
                    </div>
                </div>
            </div>
        </div>
        <div class='main-text'>
            <p class='main-content'><b>지역기반 외주 플랫폼 로컬리지는 지역 스타트업의 과업을 지역민 or<br><br><br> 지역 대학생을 통해서 해결할 뿐만 아니라 1회사, 1프리랜서 고용을 지원해 드립니다.</b></p>
        </div>
    
        <div class='proccess'>
            <div class='proccess-title'>
                <h2><b>로컬리지는 <span class='proccess-title-focus'>이런 점</span> 이 달라요!</b></h2>
            </div>
            <div class='proccess-content'>
                <div class='row'>
                    <div class='col'>
                        <img src="<%= asset_path( 'copywrite.jpg' ) %>" width=350 heigh=350 /><br>
                        <h5><b>1. 프리랜서 저작권 교육</b></h5>
                        <p>글씨, 사진 등의 저작권 교육 진행</p>
                    </div>
                    <div class='col'>
                        <img src="<%= asset_path( 'insincere.jpg' ) %>" width=330 heigh=350 /><br>
                        <h5><b>2. 불성실한 프리랜서 퇴출</b></h5>
                        <p>3번 작업기한, 월 문제 시 프리랜서 퇴출</p>
                    </div>
                    <div class='col'>
                        <img src="<%= asset_path( 'afterservice.jpg' ) %>" width=350 heigh=350 /><br>
                        <h5><b>3. A/S 사후 관리</b></h5>
                        <p>작업기한 내 완료 불가 시 로컬리지에서 작업 진행</p>
                    </div>
                </div>
            </div>
            <div class='proccess2'>
                <div class='proccess2-title'>
                    <h1><b>PR<span class='proccess2-title-focus'>O</span>CCESS</b></h1>
                </div>
                
                <img src="<%= asset_path( 'proccess.png' ) %>" />
            </div>
        </div>
    </div>
</div>

app/views/freelancers/new.html.erb
<div class="new-category">
    <div class="container">
        <%= form_for :category, url: category_path do |f| %>
            <%= f.select(:category, ['영상', '디자인'], {:class => 'form-control'}) %>
            <%= f.submit %>
        <% end %>
    </div>
</div>

app/views/freelancers/promotion.html.erb
<div class="promotion">
    <div class="container">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">블로그이름</th>
                        <th scope="col">분야</th>
                        <th scope="col">링크</th>
                    </tr>
                </thead>
                <% @promotions.each do |promotion| %>
                    <tbody>
                        <tr>
                            <td><%= promotion.title %></td>
                            <td><%= promotion.category %></td>
                            <td><a href="<%= promotion.blog %>" target="_blank"><%= promotion.blog %></a></td>
                            <td><a href="/promotion/<%= promotion.id %>/delete">삭제</a></td>
                        </tr>
                    </tbody>
                <% end %>
            </table>
    </div>
    
    <% if !current_user.nil? %>
        <% if current_user.has_role? :admin %>
            <div class="new-content">
              <div class="container">
                <%= form_for(@promotion, url:  promotion_create_path, method: :post) do |f| %>
                    
                    <%= f.label :title %>
                    <%= f.text_field :title %>
                    
                    <%= f.label :category %>
                    <%= f.text_field :category %>
                    
                    <%= f.label :blog %>
                    <%= f.text_field :blog %>
            
                 <div class="actions">
                   <%= f.submit %>
                 </div>
                <% end %>
              </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/freelancers/ready.html.erb
<div class="container">
    <div class="about">
        <img src="<%= asset_path( 'fucntion.png' ) %>" alt="logo" />
    </div>
</div>

app/views/freelancers/video.html.erb
<div class="index">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <div class="category">
                    <img src="<%= asset_path( 'video-index.png' ) %>" /><br>
                    <img src="<%= asset_path( 'login-bar1.png' ) %>" /><br>
                    <img src="<%= asset_path( 'category.png' ) %>" /><br>
                    <img src="<%= asset_path( 'login-bar3.png' ) %>" /><br>
                </div>
            </div>
            
            <div class="col-8">
                <div>
                    <img src="<%= asset_path( 'video-category.png' ) %>" />
                </div>
                <div>
                    <% @videos.each do |video| %>
                        <div class="product-list">
                            <a href="/video/show/<%= video.id %>">
                                <div class="row">
                                    <div class="col-4">
                                        <div class="index-image">
                                            <img src="<%= video.locallage.medium.url %>" width=300 weight=300 >
                                        </div>
                                    </div>
                                    <div class="col-8">
                                        <div class="product-content">
                                            <p class="index-title">
                                                <%= video.title %>
                                            </p>
                                            <hr>
                                            <p>
                                                <span class="index-university"><%= video.university %>대학교</span>
                                                <span class="index-grade"><%= video.grade %>학년</span>
                                                <span class="index-name"><%= video.name %></span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/freelancers/video_edit.html.erb
<%= form_for(@video, :html => { :multipart => true }, url: "/video/show/#{@video.id}/update", method: :patch ) do |f| %>

    <%= f.label :locallage %>
    <%= f.file_field :locallage %>
    
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :university %>
    <%= f.text_field :university %>
    
    <%= f.label :grade %>
    <%= f.text_field :grade %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :video_url %>
      <%= f.text_field :video_url %>
      
    <%= f.label :content %>
    <%= f.text_area :content %>>

    <%= f.fields_for :video_attachments do |p| %>
      <div class="field">
        <%= p.label :portfolio %><br>
        <%= p.file_field :portfolio, :multiple => true, name: "video_attachments[portfolio][]" %>
      </div>
    <% end %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/freelancers/video_new.html.erb
<div class="new-content">
  <div class="container">
    <%= form_for(@video, :html => { :multipart => true }, url: video_create_path) do |f| %>
    
      <%= f.label :locallage %>
      <%= f.file_field :locallage %><br>
      
      <%= f.label :title %>
      <%= f.text_field :title %><br>
    
      <%= f.label :university %>
      <%= f.text_field :university %><br>
    
      <%= f.label :grade %>
      <%= f.text_field :grade %><br>
      
      <%= f.label :name %>
      <%= f.text_field :name %><br>
      
      <%= f.label :video_url %>
      <%= f.text_field :video_url %>
      https://www.youtube.com/embed/<br>
    
      <%= f.label :content %>
      <%= f.text_area :content %><br>
      
    
      <%= f.hidden_field :user_id, value: current_user.id %>

      <%= f.fields_for :video_attachments do |p| %>
      <div class="field">
        <%= p.label :portfolio %><br>
        <%= p.file_field :portfolio, :multiple => true, name: "video_attachments[portfolio][]" %>
      </div>
      <% end %>

     <div class="actions">
       <%= f.submit %>
     </div>
    <% end %>
  </div>
</div>